// Runes store for LOCALLY-GENERATED session titles. Each agent card's title is a
// short focus description (e.g. "Improve dialog handling", or "PROJ-45: Fix login"
// when a ticket is referenced) generated by the on-device model from the USER's
// messages in that session's transcript — re-derived only when they actually change.
//
// The Rust `session_focus(sessionId, cwd, cloudFallback)` command does the model call
// (extract the user's messages → ask the local `llama-server` polish model; and, when
// the opt-in `titles.cloudFallback` setting is on, fall back to `claude -p` Haiku if the
// on-device model is unavailable). It's gated entirely on the
// transcript's `user_hash` (from the activity store): a title is (re)requested
// only when that hash differs from the one we already titled, and at most once per
// throttle window per pane, so an active session never spams the model.

import { invoke } from '@tauri-apps/api/core';
import type { PaneRef } from './activity.svelte';
import { titleSettings } from '$lib/settings/titles.svelte';

/**
 * Min interval between title requests for one pane (ms) — a small FLOOR, not a
 * long cool-down. The title is gated on the transcript's user-message hash, so a
 * NEW user message (changed hash) must re-derive the title PROMPTLY rather than
 * waiting out a long window. We keep only a few-seconds floor to coalesce a rapid
 * burst of polls / messages into one request and avoid re-deriving mid-stream;
 * 3 s is short enough to feel immediate after a message yet long enough to
 * absorb the ~per-second activity poll and back-to-back edits. (Was 120_000 — a
 * 2-minute window that wrongly blocked refreshing the title for up to 2 min after
 * the user had already sent a new message.)
 */
export const TITLE_THROTTLE_MS = 3_000;

/**
 * Min interval between TERMINAL title requests for one pane. Longer than the
 * session floor: a terminal's change key moves on every command (a session's on
 * every user message), so a burst of quick commands coalesces into one title.
 */
export const TERMINAL_THROTTLE_MS = 10_000;

/**
 * How long to park a terminal pane after a FAILED request (no local model, the
 * sidecar won't start). Without a backoff the throttle alone would retry every
 * few seconds for the life of the app, once per open terminal.
 */
export const TERMINAL_RETRY_MS = 300_000;

/** localStorage key for the persisted, sessionId-keyed title cache. */
const STORAGE_KEY = 'agent-desktop:session-titles';

/** A pane's cached title + the user-hash it was generated for. */
export interface TitleEntry {
  title: string | null;
  hash: string | null;
  /**
   * Set when the user gave this session a CUSTOM title (header inline-edit or the
   * agent card's "Rename" menu). A manual title is STICKY: it displays in place of
   * any auto-generated title and `shouldRequest` returns false for it forever, so
   * later messages never re-generate it. Persisted (under sessionId) so it survives
   * restart/resume. Absent/false for auto-generated titles.
   */
  manual?: boolean;
}

/** Load the persisted sessionId -> entry cache (survives restart / resume). */
function loadPersisted(): Record<string, TitleEntry> {
  if (typeof localStorage === 'undefined') return {};
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return {};
    const parsed = JSON.parse(raw) as Record<string, TitleEntry>;
    return parsed && typeof parsed === 'object' ? parsed : {};
  } catch {
    return {};
  }
}

/**
 * PURE: whether to (re)request a title for a pane. Requests when the user has
 * messages (`userHash` is set) and the current title is for a DIFFERENT hash, we
 * are not already fetching that same hash, and the throttle window has elapsed.
 * A MANUAL (custom) title is sticky — auto-generation stops for it permanently.
 */
export function shouldRequest(
  entry: TitleEntry | undefined,
  pendingHash: string | undefined,
  userHash: string | null,
  lastAttempt: number,
  nowMs: number,
  throttleMs: number = TITLE_THROTTLE_MS
): boolean {
  if (entry?.manual) return false; // custom title — never auto-regenerate it
  if (!userHash) return false;
  if (entry?.hash === userHash) return false; // already titled for this hash
  if (pendingHash === userHash) return false; // already fetching this hash
  if (nowMs - lastAttempt < throttleMs) return false; // throttle
  return true;
}

/** One terminal row to title / hydrate. */
export interface TerminalTitleRef {
  /** The live pane id (the runtime title key). */
  paneId: string;
  /**
   * The DURABLE title key, or null when there is none. A task terminal passes
   * `task:<defId>` (stable across restarts, so a custom title survives); a bare
   * shell passes null — its id is per-process, exactly like the lane order that
   * also omits terminal ids, so its title lives only for that process.
   */
  key: string | null;
  /**
   * The commands the user has typed in this terminal (newline-joined, oldest
   * first), or null when nothing has been typed / the row should not be titled by
   * the model (a task terminal). Doubles as the change key.
   */
  commands: string | null;
}

/**
 * PURE: whether committing a rename should WRITE a custom title. A draft that
 * differs from the shown name always does; a draft that MATCHES it does too
 * unless the shown name is already the user's own — typing a row's current name
 * is how you PIN it against the generator (a bare shell is literally called
 * "Terminal", the very name a user would retype to stop it from being renamed
 * out from under them). An empty draft never commits (`setManualTitle` also
 * ignores it) so a rename can't blank a name.
 */
export function shouldCommitRename(draft: string, shown: string, isManual: boolean): boolean {
  const trimmed = draft.trim();
  if (!trimmed) return false;
  return trimmed !== shown || !isManual;
}

/** Reactive title store: paneId -> {title, hash}. */
export class TitleStore {
  byPane = $state<Record<string, TitleEntry>>({});
  // The DURABLE cache, keyed by sessionId (stable across restart/resume). The
  // paneId-keyed `byPane` is hydrated from here on `refresh` so a restored agent
  // shows its last title immediately, with no model call.
  #bySession: Record<string, TitleEntry> = loadPersisted();
  #pending = new Map<string, string>();
  #lastAttempt = new Map<string, number>();
  // Terminal-only bookkeeping: panes we have titled (so their entries can be
  // reclaimed when the terminal goes away) and a per-pane failure backoff.
  #terminalPanes = new Set<string>();
  #retryAfter = new Map<string, number>();

  /** Whether a pane's shown title is the user's own (a rename), rather than
   *  generated or absent. Lets a caller tell "already pinned by the user" from
   *  "just happens to match the current title". */
  isManual(paneId: string): boolean {
    return this.byPane[paneId]?.manual === true;
  }

  /** The generated title for a pane, or null when none yet. */
  titleFor(paneId: string): string | null {
    return this.byPane[paneId]?.title ?? null;
  }

  /**
   * Set a user-chosen CUSTOM title for a session (header inline-edit or the agent
   * card's "Rename" menu). Updates the runtime `byPane` cache so it shows at once,
   * marks the entry `manual` so `shouldRequest` never re-generates it, and PERSISTS
   * it under `sessionId` (durable, survives restart/resume — it's reloaded into
   * `byPane` by `hydrate`). An empty/whitespace title is ignored (no-op): a custom
   * title can never blank out the displayed name.
   */
  setManualTitle(paneId: string, sessionId: string | null, title: string): void {
    const trimmed = title.trim();
    if (!trimmed) return; // ignore empty — never clear the shown title
    // A manual title is hash-independent (it never re-generates), so we don't pin
    // it to a userHash; `manual` is the sole gate `shouldRequest` reads.
    const entry: TitleEntry = { title: trimmed, hash: null, manual: true };
    this.byPane[paneId] = entry;
    if (sessionId) {
      this.#bySession[sessionId] = entry;
      this.#persist();
    }
  }

  /**
   * Seed runtime titles from the durable, sessionId-keyed cache for any pane that
   * isn't titled yet. PURE cache read — no model call, no userHash needed — so a
   * restored agent renders its previous title IMMEDIATELY on mount, before the
   * first (async) activity poll runs. Without this, `titleFor` returns null until
   * the poll completes and the card falls back to its "Session N" name for a beat.
   * Idempotent and called both on mount and at the top of every `refresh`.
   */
  hydrate(panes: PaneRef[]): void {
    for (const p of panes) {
      if (!this.byPane[p.paneId] && p.sessionId) {
        const saved = this.#bySession[p.sessionId];
        if (saved) this.byPane[p.paneId] = saved;
      }
    }
  }

  /**
   * For each pane, request a fresh session title when the user's messages changed
   * (per `hashOf(paneId)`), subject to the per-pane throttle. Fire-and-forget; the
   * store updates reactively when each title resolves.
   */
  refresh(panes: PaneRef[], hashOf: (paneId: string) => string | null | undefined, nowMs: number): void {
    // Seed from the durable cache first so a restored agent shows its previous
    // title at once (and we skip the model call when its messages are unchanged).
    this.hydrate(panes);
    for (const p of panes) {
      const userHash = hashOf(p.paneId) ?? null;
      const entry = this.byPane[p.paneId];
      const pending = this.#pending.get(p.paneId);
      const last = this.#lastAttempt.get(p.paneId) ?? 0;
      if (!shouldRequest(entry, pending, userHash, last, nowMs)) continue;
      this.#pending.set(p.paneId, userHash as string);
      this.#lastAttempt.set(p.paneId, nowMs);
      void this.#fetch(p, userHash as string);
    }
  }

  async #fetch(pane: PaneRef, hash: string): Promise<void> {
    try {
      const title = await invoke<string | null>('session_focus', {
        sessionId: pane.sessionId,
        cwd: pane.cwd,
        // Opt-in: allow the backend to fall back to `claude -p` (Haiku) when the
        // on-device title model is unavailable. Off by default (on-device only).
        cloudFallback: titleSettings.prefs.cloudFallback,
        // Per-backend transcript source (`session-titles`): copilot titles are
        // generated from the copilot session event log.
        program: pane.program ?? null
      });
      // Bail if the user gave this session a CUSTOM title while we were awaiting:
      // a manual title is sticky and must NEVER be clobbered by a now-stale
      // auto-generation that was already in flight when the rename happened.
      if (this.byPane[pane.paneId]?.manual) return;
      if (pane.sessionId && this.#bySession[pane.sessionId]?.manual) return;
      const next: TitleEntry = { title: title ?? null, hash };
      this.byPane[pane.paneId] = next;
      // Persist a resolved title under its sessionId so it survives a restart.
      if (pane.sessionId && next.title) {
        this.#bySession[pane.sessionId] = next;
        this.#persist();
      }
    } catch (err) {
      console.warn('session_focus failed; keeping previous title:', err);
    } finally {
      if (this.#pending.get(pane.paneId) === hash) this.#pending.delete(pane.paneId);
    }
  }

  /**
   * Seed a TERMINAL row's title from the durable cache (`session-titles`: "Bare
   * terminal rows are titled from the commands the user ran"). Same idea as
   * `hydrate`, but keyed by the row's TITLE KEY rather than a session id: a task
   * terminal's key (`task:<defId>`) is stable, so a restarted task terminal — a
   * NEW pane id — shows its previous (usually custom) title with no model call. A
   * bare shell passes `key: null` (its id is per-process and never persisted), so
   * it is simply skipped here.
   */
  hydrateKeys(refs: ReadonlyArray<TerminalTitleRef>): void {
    for (const r of refs) {
      if (!this.byPane[r.paneId] && r.key) {
        const saved = this.#bySession[r.key];
        if (saved) this.byPane[r.paneId] = saved;
      }
    }
  }

  /**
   * Request titles for TERMINAL rows whose typed-command list changed. The command
   * text plays the role a session's `user_hash` plays: it changes only when the
   * user actually runs something, so a noisy terminal (a build, `tail -f`) never
   * re-triggers a title. A ref with `commands: null` (nothing typed yet, or a task
   * terminal, whose command already IS its name) is skipped, and a manual title
   * stays sticky through `shouldRequest`. Fire-and-forget.
   */
  refreshTerminals(refs: ReadonlyArray<TerminalTitleRef>, nowMs: number): void {
    this.hydrateKeys(refs);
    this.#evictGoneTerminals(refs);
    for (const r of refs) {
      const entry = this.byPane[r.paneId];
      const pending = this.#pending.get(r.paneId);
      const last = this.#lastAttempt.get(r.paneId) ?? 0;
      // A pane whose last request FAILED (no model installed, sidecar down) is
      // parked until its backoff expires: without this the 3 s floor alone would
      // retry — and lazily re-spawn the sidecar — every few seconds, forever.
      if (nowMs < (this.#retryAfter.get(r.paneId) ?? 0)) continue;
      if (!shouldRequest(entry, pending, r.commands, last, nowMs, TERMINAL_THROTTLE_MS)) continue;
      this.#pending.set(r.paneId, r.commands as string);
      this.#lastAttempt.set(r.paneId, nowMs);
      void this.#fetchTerminal(r, r.commands as string);
    }
  }

  /** Forget every terminal pane we have seen that is no longer listed: a bare
   *  shell's pane id dies with its process, so without this the runtime caches
   *  would grow for the life of the app. Only panes THIS method registered are
   *  dropped, so session entries are untouched. */
  #evictGoneTerminals(refs: ReadonlyArray<TerminalTitleRef>): void {
    const live = new Set(refs.map((r) => r.paneId));
    for (const paneId of this.#terminalPanes) {
      if (live.has(paneId)) continue;
      this.#terminalPanes.delete(paneId);
      delete this.byPane[paneId];
      this.#pending.delete(paneId);
      this.#lastAttempt.delete(paneId);
      this.#retryAfter.delete(paneId);
    }
    for (const paneId of live) this.#terminalPanes.add(paneId);
  }

  async #fetchTerminal(ref: TerminalTitleRef, commands: string): Promise<void> {
    try {
      // ON-DEVICE ONLY — deliberately no cloud fallback. `titles.cloudFallback` is
      // the user's opt-in for sending their SESSION transcript off-device; shell
      // command lines are a different kind of data (tokens, connection strings)
      // and are not covered by that consent, so a terminal title is simply skipped
      // when the local model is unavailable.
      const title = await invoke<string | null>('terminal_focus', { commands });
      // A rename that landed while we were awaiting wins — a custom title is sticky.
      if (this.byPane[ref.paneId]?.manual) return;
      if (ref.key && this.#bySession[ref.key]?.manual) return;
      // Drop a STALE response: the user ran more commands while this was in
      // flight, a newer request took over `#pending`, and it may already have
      // resolved — writing now would revert the row to an older title and leave
      // the hash mismatched, re-firing on the next tick.
      if (this.#pending.get(ref.paneId) !== commands) return;
      const next: TitleEntry = { title: title ?? null, hash: commands };
      this.byPane[ref.paneId] = next;
      // Only a DURABLE key is persisted: a bare shell's id dies with its process.
      if (ref.key && next.title) {
        this.#bySession[ref.key] = next;
        this.#persist();
      }
    } catch (err) {
      this.#retryAfter.set(ref.paneId, Date.now() + TERMINAL_RETRY_MS);
      console.warn('terminal_focus failed; keeping previous title:', err);
    } finally {
      if (this.#pending.get(ref.paneId) === commands) this.#pending.delete(ref.paneId);
    }
  }

  /** Write the durable sessionId-keyed cache to localStorage (best-effort). */
  #persist(): void {
    if (typeof localStorage === 'undefined') return;
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(this.#bySession));
    } catch {
      /* ignore quota / disabled storage */
    }
  }
}

/** Singleton, imported by the route + the overview card. */
export const titles = new TitleStore();
