// Runes store for HAIKU-GENERATED session titles. Each agent card's title is a
// short focus description ("SKIPA-45: Fix Feature", "Improve frontend dialog
// handling") generated by Claude Haiku from the USER's messages in that session's
// transcript — re-derived only when the user's messages actually change.
//
// The Rust `session_focus(sessionId, cwd)` command does the model call (extract
// the user's messages → ask `claude -p --model haiku`). It's gated entirely on the
// transcript's `user_hash` (from the activity store): a title is (re)requested
// only when that hash differs from the one we already titled, and at most once per
// throttle window per pane, so an active session never spams the model.

import { invoke } from '@tauri-apps/api/core';
import type { PaneRef } from './activity.svelte';

/** Min interval between title requests for one pane (ms). */
export const TITLE_THROTTLE_MS = 15_000;

/** A pane's cached title + the user-hash it was generated for. */
export interface TitleEntry {
  title: string | null;
  hash: string | null;
}

/**
 * PURE: whether to (re)request a title for a pane. Requests when the user has
 * messages (`userHash` is set) and the current title is for a DIFFERENT hash, we
 * are not already fetching that same hash, and the throttle window has elapsed.
 */
export function shouldRequest(
  entry: TitleEntry | undefined,
  pendingHash: string | undefined,
  userHash: string | null,
  lastAttempt: number,
  nowMs: number,
  throttleMs: number = TITLE_THROTTLE_MS
): boolean {
  if (!userHash) return false;
  if (entry?.hash === userHash) return false; // already titled for this hash
  if (pendingHash === userHash) return false; // already fetching this hash
  if (nowMs - lastAttempt < throttleMs) return false; // throttle
  return true;
}

/** Reactive title store: paneId -> {title, hash}. */
export class TitleStore {
  byPane = $state<Record<string, TitleEntry>>({});
  #pending = new Map<string, string>();
  #lastAttempt = new Map<string, number>();

  /** The generated title for a pane, or null when none yet. */
  titleFor(paneId: string): string | null {
    return this.byPane[paneId]?.title ?? null;
  }

  /**
   * For each pane, request a fresh Haiku title when the user's messages changed
   * (per `hashOf(paneId)`), subject to the per-pane throttle. Fire-and-forget; the
   * store updates reactively when each title resolves.
   */
  refresh(panes: PaneRef[], hashOf: (paneId: string) => string | null | undefined, nowMs: number): void {
    for (const p of panes) {
      const userHash = hashOf(p.paneId) ?? null;
      const entry = this.byPane[p.paneId];
      const pending = this.#pending.get(p.paneId);
      const last = this.#lastAttempt.get(p.paneId) ?? 0;
      if (!shouldRequest(entry, pending, userHash, last, nowMs)) continue;
      this.#pending.set(p.paneId, userHash as string);
      this.#lastAttempt.set(p.paneId, nowMs);
      void this.#fetch(p, userHash as string);
    }
  }

  async #fetch(pane: PaneRef, hash: string): Promise<void> {
    try {
      const title = await invoke<string | null>('session_focus', {
        sessionId: pane.sessionId,
        cwd: pane.cwd
      });
      this.byPane[pane.paneId] = { title: title ?? null, hash };
    } catch (err) {
      console.warn('session_focus failed; keeping previous title:', err);
    } finally {
      if (this.#pending.get(pane.paneId) === hash) this.#pending.delete(pane.paneId);
    }
  }
}

/** Singleton, imported by the route + the overview card. */
export const titles = new TitleStore();
